spring.application.name=weeklybite

spring.datasource.url = jdbc:postgresql://localhost:5432/weeklybite
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8083
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.stream-write-constraints.max-nesting-depth=2000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diirrektorr@gmail.com
spring.mail.password=nwtz qrso bdli qfpn
invitations.ttl-days=7
frontend.base-url=http://localhost:4200
mobile.deep-link.scheme=weeklybite
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.task.scheduling.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=true

spring.jpa.show-sql = true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#spring.security.user.name=test
#spring.security.user.password=test
jwt.secret=l5i9a1m7e3

app.base-url=http://localhost:8080

# The path to the folder where the uploaded files will be stored.
file.upload-dir=./uploads
# Base URL path to serve these images.
# http://localhost:8080/images/your_image.jpg
file.serving-path=/images/
server.address=0.0.0.0
server.host.local=http://192.168.0.30
